site_name: gradle refreshVersions
site_url: https://jmfayard.github.io/refreshVersions/
repo_name: refreshVersions
repo_url: https://github.com/jmfayard/refreshVersions
site_description: "Life is too short to google for dependencies and versions"
site_author: jmfayard LouisCAD
remote_branch: gh-pages
edit_uri: "https://github.com/jmfayard/refreshVersions/edit/release/docs"

copyright: 'Copyright &copy; 2020-2021 jmfayard'

theme:
  name: 'material'

nav:
  - 'Overview': index.md

plugins:
  - search
  - markdownextradata: {}